application: rodrigomelendez3
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  

  
- url: /images
  static_dir: static/images
  
- url: /stylesheets
  static_dir: stylesheets
   

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: yaml
  version: "latest"
  
- name: jinja2
  version: "latest"
  
- name: PIL
  version: "1.1.7"  

- name: numpy
  version: "latest"


builtins:
#- datastore_admin: on